package com.pixelservices.flash;

import com.pixelservices.flash.components.FlashConfiguration;
import com.pixelservices.flash.components.FlashServer;
import com.pixelservices.flash.models.HandlerType;
import com.pixelservices.flash.swagger.OpenAPIConfiguration;
import com.pixelservices.flash.swagger.OpenAPIUITemplate;
import com.pixelservices.flash.test.HelloWorld;
import com.pixelservices.flash.test.TestHandler;

import java.net.InetSocketAddress;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        final int PORT = args.length > 0 ? Integer.parseInt(args[0]) : 4005;

        FlashConfiguration config = new FlashConfiguration();
        config.setLoggingPreference(HandlerType.STATIC, false);

        FlashServer server = new FlashServer(PORT, config);

        server.get("/hello/:myParam", (req, res) -> {
            InetSocketAddress addr = req.clientAddress();
            return "Hello, " + req.getRouteParam("myParam") + " from " + addr.getHostName() + ":" + addr.getPort();
        });

        server.get("/dynamic/*", (req, res) -> {
            return req.path();
        });

        server.route("/test")
              .register(TestHandler.class)
              .register(HelloWorld.class);

        server.openapi("/docs", new OpenAPIConfiguration(
            "Flash Server",
            "Generated by Flash!",
            "1.0",
            List.of("http://localhost:" + PORT)
        ), OpenAPIUITemplate.SWAGGER_UI);

        server.start();
    }
}

