name: Deploy Javadocs

on:
    release:
        types: [published]
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            # Step 1: Check out the code
            - uses: actions/checkout@v4

            # Step 2: Set up Java
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            # Step 3: Cache Maven dependencies
            - name: Cache local Maven repository
              uses: actions/cache@v4
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            # Step 4: Build Javadocs with Maven
            - name: Build Javadocs
              run: mvn -B javadoc:javadoc

            # Step 5: Deploy Javadocs
            - name: Deploy JavaDoc 🚀
              uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  javadoc-branch: javadoc
                  java-version: 21
                  target-folder: javadoc
                  project: maven
