name: Deploy Javadocs

on:
    release:
        types: [published]
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Deploy JavaDoc 🚀
              uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  javadoc-branch: javadoc
                  java-version: 21
                  target-folder: javadoc
                  project: maven
